version: "3.7"
services:
  #MongoDB
  database-mongodb:
    image: mongo:4.2-bionic
    container_name: mongo-db
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=cortex
      - MONGO_INITDB_ROOT_USERNAME=cortex
      - MONGO_INITDB_ROOT_PASSWORD=cortex
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - 27017:27017
    networks:
      - backend
    restart: always
    volumes:
      - mongodb-volume:/data/db
volumes:
  mongodb-volume:
networks:
  backend:
    driver: bridge
